on:
  push:
    tags:
      - 'v*'

jobs:
  update-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clona registry
        run: |
          if [ -z "${{ secrets.REGISTRY_PAT }}" ]; then
            echo "Error: REGISTRY_PAT secret is not set."
            exit 1
          fi
          git clone https://${{ secrets.REGISTRY_PAT }}@github.com/romanharen1/vcpkg_registry.git
          cd vcpkg_registry
          chmod +x scripts/update-ports.sh

      - name: Atualiza portfile
        run: |
          cd vcpkg_registry/scripts
          ./update-ports.sh ${{ github.repository }} ${{ github.ref_name }}

      - name: Commit e push para registry
        run: |
          cd vcpkg_registry
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Atualiza port para versão ${{ github.ref_name }}"
          git push
